class Country:


	country_code_name_dictionary = {}
	country_code_name_dictionary["AD"] = {"code": "376", "name": "ANDORRA"}
	country_code_name_dictionary["AE"] = {"code": "971", "name": "UNITED ARAB EMIRATES"}
	country_code_name_dictionary["AF"] = {"code": "93", "name": "AFGHANISTAN"}
	country_code_name_dictionary["AG"] = {"code": "1268", "name": "ANTIGUA AND BARBUDA"}
	country_code_name_dictionary["AI"] = {"code": "1264", "name": "ANGUILLA"}
	country_code_name_dictionary["AL"] = {"code": "355", "name": "ALBANIA"}
	country_code_name_dictionary["AM"] = {"code": "374", "name": "ARMENIA"}
	country_code_name_dictionary["AN"] = {"code": "599", "name": "NETHERLANDS ANTILLES"}
	country_code_name_dictionary["AO"] = {"code": "244", "name": "ANGOLA"}
	country_code_name_dictionary["AQ"] = {"code": "672", "name": "ANTARCTICA"}
	country_code_name_dictionary["AR"] = {"code": "54", "name": "ARGENTINA"}
	country_code_name_dictionary["AS"] = {"code": "1684", "name": "AMERICAN SAMOA"}
	country_code_name_dictionary["AT"] = {"code": "43", "name": "AUSTRIA"}
	country_code_name_dictionary["AU"] = {"code": "61", "name": "AUSTRALIA"}
	country_code_name_dictionary["AW"] = {"code": "297", "name": "ARUBA"}
	country_code_name_dictionary["AZ"] = {"code": "994", "name": "AZERBAIJAN"}
	country_code_name_dictionary["BA"] = {"code": "387", "name": "BOSNIA AND HERZEGOVINA"}
	country_code_name_dictionary["BB"] = {"code": "1246", "name": "BARBADOS"}
	country_code_name_dictionary["BD"] = {"code": "880", "name": "BANGLADESH"}
	country_code_name_dictionary["BE"] = {"code": "32", "name": "BELGIUM"}
	country_code_name_dictionary["BF"] = {"code": "226", "name": "BURKINA FASO"}
	country_code_name_dictionary["BG"] = {"code": "359", "name": "BULGARIA"}
	country_code_name_dictionary["BH"] = {"code": "973", "name": "BAHRAIN"}
	country_code_name_dictionary["BI"] = {"code": "257", "name": "BURUNDI"}
	country_code_name_dictionary["BJ"] = {"code": "229", "name": "BENIN"}
	country_code_name_dictionary["BL"] = {"code": "590", "name": "SAINT BARTHELEMY"}
	country_code_name_dictionary["BM"] = {"code": "1441", "name": "BERMUDA"}
	country_code_name_dictionary["BN"] = {"code": "673", "name": "BRUNEI DARUSSALAM"}
	country_code_name_dictionary["BO"] = {"code": "591", "name": "BOLIVIA"}
	country_code_name_dictionary["BR"] = {"code": "55", "name": "BRAZIL"}
	country_code_name_dictionary["BS"] = {"code": "1242", "name": "BAHAMAS"}
	country_code_name_dictionary["BT"] = {"code": "975", "name": "BHUTAN"}
	country_code_name_dictionary["BW"] = {"code": "267", "name": "BOTSWANA"}
	country_code_name_dictionary["BY"] = {"code": "375", "name": "BELARUS"}
	country_code_name_dictionary["BZ"] = {"code": "501", "name": "BELIZE"}
	country_code_name_dictionary["CA"] = {"code": "1", "name": "CANADA"}
	country_code_name_dictionary["CC"] = {"code": "61", "name": "COCOS (KEELING) ISLANDS"}
	country_code_name_dictionary["CD"] = {"code": "243", "name": "CONGO, THE DEMOCRATIC REPUBLIC OF THE"}
	country_code_name_dictionary["CF"] = {"code": "236", "name": "CENTRAL AFRICAN REPUBLIC"}
	country_code_name_dictionary["CG"] = {"code": "242", "name": "CONGO"}
	country_code_name_dictionary["CH"] = {"code": "41", "name": "SWITZERLAND"}
	country_code_name_dictionary["CI"] = {"code": "225", "name": "COTE D IVOIRE"}
	country_code_name_dictionary["CK"] = {"code": "682", "name": "COOK ISLANDS"}
	country_code_name_dictionary["CL"] = {"code": "56", "name": "CHILE"}
	country_code_name_dictionary["CM"] = {"code": "237", "name": "CAMEROON"}
	country_code_name_dictionary["CN"] = {"code": "86", "name": "CHINA"}
	country_code_name_dictionary["CO"] = {"code": "57", "name": "COLOMBIA"}
	country_code_name_dictionary["CR"] = {"code": "506", "name": "COSTA RICA"}
	country_code_name_dictionary["CU"] = {"code": "53", "name": "CUBA"}
	country_code_name_dictionary["CV"] = {"code": "238", "name": "CAPE VERDE"}
	country_code_name_dictionary["CX"] = {"code": "61", "name": "CHRISTMAS ISLAND"}
	country_code_name_dictionary["CY"] = {"code": "357", "name": "CYPRUS"}
	country_code_name_dictionary["CZ"] = {"code": "420", "name": "CZECH REPUBLIC"}
	country_code_name_dictionary["DE"] = {"code": "49", "name": "GERMANY"}
	country_code_name_dictionary["DJ"] = {"code": "253", "name": "DJIBOUTI"}
	country_code_name_dictionary["DK"] = {"code": "45", "name": "DENMARK"}
	country_code_name_dictionary["DM"] = {"code": "1767", "name": "DOMINICA"}
	country_code_name_dictionary["DO"] = {"code": "1809", "name": "DOMINICAN REPUBLIC"}
	country_code_name_dictionary["DZ"] = {"code": "213", "name": "ALGERIA"}
	country_code_name_dictionary["EC"] = {"code": "593", "name": "ECUADOR"}
	country_code_name_dictionary["EE"] = {"code": "372", "name": "ESTONIA"}
	country_code_name_dictionary["EG"] = {"code": "20", "name": "EGYPT"}
	country_code_name_dictionary["ER"] = {"code": "291", "name": "ERITREA"}
	country_code_name_dictionary["ES"] = {"code": "34", "name": "SPAIN"}
	country_code_name_dictionary["ET"] = {"code": "251", "name": "ETHIOPIA"}
	country_code_name_dictionary["FI"] = {"code": "358", "name": "FINLAND"}
	country_code_name_dictionary["FJ"] = {"code": "679", "name": "FIJI"}
	country_code_name_dictionary["FK"] = {"code": "500", "name": "FALKLAND ISLANDS (MALVINAS)"}
	country_code_name_dictionary["FM"] = {"code": "691", "name": "MICRONESIA, FEDERATED STATES OF"}
	country_code_name_dictionary["FO"] = {"code": "298", "name": "FAROE ISLANDS"}
	country_code_name_dictionary["FR"] = {"code": "33", "name": "FRANCE"}
	country_code_name_dictionary["GA"] = {"code": "241", "name": "GABON"}
	country_code_name_dictionary["GB"] = {"code": "44", "name": "UNITED KINGDOM"}
	country_code_name_dictionary["GD"] = {"code": "1473", "name": "GRENADA"}
	country_code_name_dictionary["GE"] = {"code": "995", "name": "GEORGIA"}
	country_code_name_dictionary["GH"] = {"code": "233", "name": "GHANA"}
	country_code_name_dictionary["GI"] = {"code": "350", "name": "GIBRALTAR"}
	country_code_name_dictionary["GL"] = {"code": "299", "name": "GREENLAND"}
	country_code_name_dictionary["GM"] = {"code": "220", "name": "GAMBIA"}
	country_code_name_dictionary["GN"] = {"code": "224", "name": "GUINEA"}
	country_code_name_dictionary["GQ"] = {"code": "240", "name": "EQUATORIAL GUINEA"}
	country_code_name_dictionary["GR"] = {"code": "30", "name": "GREECE"}
	country_code_name_dictionary["GT"] = {"code": "502", "name": "GUATEMALA"}
	country_code_name_dictionary["GU"] = {"code": "1671", "name": "GUAM"}
	country_code_name_dictionary["GW"] = {"code": "245", "name": "GUINEA-BISSAU"}
	country_code_name_dictionary["GY"] = {"code": "592", "name": "GUYANA"}
	country_code_name_dictionary["HK"] = {"code": "852", "name": "HONG KONG"}
	country_code_name_dictionary["HN"] = {"code": "504", "name": "HONDURAS"}
	country_code_name_dictionary["HR"] = {"code": "385", "name": "CROATIA"}
	country_code_name_dictionary["HT"] = {"code": "509", "name": "HAITI"}
	country_code_name_dictionary["HU"] = {"code": "36", "name": "HUNGARY"}
	country_code_name_dictionary["ID"] = {"code": "62", "name": "INDONESIA"}
	country_code_name_dictionary["IE"] = {"code": "353", "name": "IRELAND"}
	country_code_name_dictionary["IL"] = {"code": "972", "name": "ISRAEL"}
	country_code_name_dictionary["IM"] = {"code": "44", "name": "ISLE OF MAN"}
	country_code_name_dictionary["IN"] = {"code": "91", "name": "INDIA"}
	country_code_name_dictionary["IQ"] = {"code": "964", "name": "IRAQ"}
	country_code_name_dictionary["IR"] = {"code": "98", "name": "IRAN, ISLAMIC REPUBLIC OF"}
	country_code_name_dictionary["IS"] = {"code": "354", "name": "ICELAND"}
	country_code_name_dictionary["IT"] = {"code": "39", "name": "ITALY"}
	country_code_name_dictionary["JM"] = {"code": "1876", "name": "JAMAICA"}
	country_code_name_dictionary["JO"] = {"code": "962", "name": "JORDAN"}
	country_code_name_dictionary["JP"] = {"code": "81", "name": "JAPAN"}
	country_code_name_dictionary["KE"] = {"code": "254", "name": "KENYA"}
	country_code_name_dictionary["KG"] = {"code": "996", "name": "KYRGYZSTAN"}
	country_code_name_dictionary["KH"] = {"code": "855", "name": "CAMBODIA"}
	country_code_name_dictionary["KI"] = {"code": "686", "name": "KIRIBATI"}
	country_code_name_dictionary["KM"] = {"code": "269", "name": "COMOROS"}
	country_code_name_dictionary["KN"] = {"code": "1869", "name": "SAINT KITTS AND NEVIS"}
	country_code_name_dictionary["KP"] = {"code": "850", "name": "KOREA DEMOCRATIC PEOPLES REPUBLIC OF"}
	country_code_name_dictionary["KR"] = {"code": "82", "name": "KOREA REPUBLIC OF"}
	country_code_name_dictionary["KW"] = {"code": "965", "name": "KUWAIT"}
	country_code_name_dictionary["KY"] = {"code": "1345", "name": "CAYMAN ISLANDS"}
	country_code_name_dictionary["KZ"] = {"code": "7", "name": "KAZAKSTAN"}
	country_code_name_dictionary["LA"] = {"code": "856", "name": "LAO PEOPLES DEMOCRATIC REPUBLIC"}
	country_code_name_dictionary["LB"] = {"code": "961", "name": "LEBANON"}
	country_code_name_dictionary["LC"] = {"code": "1758", "name": "SAINT LUCIA"}
	country_code_name_dictionary["LI"] = {"code": "423", "name": "LIECHTENSTEIN"}
	country_code_name_dictionary["LK"] = {"code": "94", "name": "SRI LANKA"}
	country_code_name_dictionary["LR"] = {"code": "231", "name": "LIBERIA"}
	country_code_name_dictionary["LS"] = {"code": "266", "name": "LESOTHO"}
	country_code_name_dictionary["LT"] = {"code": "370", "name": "LITHUANIA"}
	country_code_name_dictionary["LU"] = {"code": "352", "name": "LUXEMBOURG"}
	country_code_name_dictionary["LV"] = {"code": "371", "name": "LATVIA"}
	country_code_name_dictionary["LY"] = {"code": "218", "name": "LIBYAN ARAB JAMAHIRIYA"}
	country_code_name_dictionary["MA"] = {"code": "212", "name": "MOROCCO"}
	country_code_name_dictionary["MC"] = {"code": "377", "name": "MONACO"}
	country_code_name_dictionary["MD"] = {"code": "373", "name": "MOLDOVA, REPUBLIC OF"}
	country_code_name_dictionary["ME"] = {"code": "382", "name": "MONTENEGRO"}
	country_code_name_dictionary["MF"] = {"code": "1599", "name": "SAINT MARTIN"}
	country_code_name_dictionary["MG"] = {"code": "261", "name": "MADAGASCAR"}
	country_code_name_dictionary["MH"] = {"code": "692", "name": "MARSHALL ISLANDS"}
	country_code_name_dictionary["MK"] = {"code": "389", "name": "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF"}
	country_code_name_dictionary["ML"] = {"code": "223", "name": "MALI"}
	country_code_name_dictionary["MM"] = {"code": "95", "name": "MYANMAR"}
	country_code_name_dictionary["MN"] = {"code": "976", "name": "MONGOLIA"}
	country_code_name_dictionary["MO"] = {"code": "853", "name": "MACAU"}
	country_code_name_dictionary["MP"] = {"code": "1670", "name": "NORTHERN MARIANA ISLANDS"}
	country_code_name_dictionary["MR"] = {"code": "222", "name": "MAURITANIA"}
	country_code_name_dictionary["MS"] = {"code": "1664", "name": "MONTSERRAT"}
	country_code_name_dictionary["MT"] = {"code": "356", "name": "MALTA"}
	country_code_name_dictionary["MU"] = {"code": "230", "name": "MAURITIUS"}
	country_code_name_dictionary["MV"] = {"code": "960", "name": "MALDIVES"}
	country_code_name_dictionary["MW"] = {"code": "265", "name": "MALAWI"}
	country_code_name_dictionary["MX"] = {"code": "52", "name": "MEXICO"}
	country_code_name_dictionary["MY"] = {"code": "60", "name": "MALAYSIA"}
	country_code_name_dictionary["MZ"] = {"code": "258", "name": "MOZAMBIQUE"}
	country_code_name_dictionary["NA"] = {"code": "264", "name": "NAMIBIA"}
	country_code_name_dictionary["NC"] = {"code": "687", "name": "NEW CALEDONIA"}
	country_code_name_dictionary["NE"] = {"code": "227", "name": "NIGER"}
	country_code_name_dictionary["NG"] = {"code": "234", "name": "NIGERIA"}
	country_code_name_dictionary["NI"] = {"code": "505", "name": "NICARAGUA"}
	country_code_name_dictionary["NL"] = {"code": "31", "name": "NETHERLANDS"}
	country_code_name_dictionary["NO"] = {"code": "47", "name": "NORWAY"}
	country_code_name_dictionary["NP"] = {"code": "977", "name": "NEPAL"}
	country_code_name_dictionary["NR"] = {"code": "674", "name": "NAURU"}
	country_code_name_dictionary["NU"] = {"code": "683", "name": "NIUE"}
	country_code_name_dictionary["NZ"] = {"code": "64", "name": "NEW ZEALAND"}
	country_code_name_dictionary["OM"] = {"code": "968", "name": "OMAN"}
	country_code_name_dictionary["PA"] = {"code": "507", "name": "PANAMA"}
	country_code_name_dictionary["PE"] = {"code": "51", "name": "PERU"}
	country_code_name_dictionary["PF"] = {"code": "689", "name": "FRENCH POLYNESIA"}
	country_code_name_dictionary["PG"] = {"code": "675", "name": "PAPUA NEW GUINEA"}
	country_code_name_dictionary["PH"] = {"code": "63", "name": "PHILIPPINES"}
	country_code_name_dictionary["PK"] = {"code": "92", "name": "PAKISTAN"}
	country_code_name_dictionary["PL"] = {"code": "48", "name": "POLAND"}
	country_code_name_dictionary["PM"] = {"code": "508", "name": "SAINT PIERRE AND MIQUELON"}
	country_code_name_dictionary["PN"] = {"code": "870", "name": "PITCAIRN"}
	country_code_name_dictionary["PR"] = {"code": "1", "name": "PUERTO RICO"}
	country_code_name_dictionary["PT"] = {"code": "351", "name": "PORTUGAL"}
	country_code_name_dictionary["PW"] = {"code": "680", "name": "PALAU"}
	country_code_name_dictionary["PY"] = {"code": "595", "name": "PARAGUAY"}
	country_code_name_dictionary["QA"] = {"code": "974", "name": "QATAR"}
	country_code_name_dictionary["RO"] = {"code": "40", "name": "ROMANIA"}
	country_code_name_dictionary["RS"] = {"code": "381", "name": "SERBIA"}
	country_code_name_dictionary["RU"] = {"code": "7", "name": "RUSSIAN FEDERATION"}
	country_code_name_dictionary["RW"] = {"code": "250", "name": "RWANDA"}
	country_code_name_dictionary["SA"] = {"code": "966", "name": "SAUDI ARABIA"}
	country_code_name_dictionary["SB"] = {"code": "677", "name": "SOLOMON ISLANDS"}
	country_code_name_dictionary["SC"] = {"code": "248", "name": "SEYCHELLES"}
	country_code_name_dictionary["SD"] = {"code": "249", "name": "SUDAN"}
	country_code_name_dictionary["SE"] = {"code": "46", "name": "SWEDEN"}
	country_code_name_dictionary["SG"] = {"code": "65", "name": "SINGAPORE"}
	country_code_name_dictionary["SH"] = {"code": "290", "name": "SAINT HELENA"}
	country_code_name_dictionary["SI"] = {"code": "386", "name": "SLOVENIA"}
	country_code_name_dictionary["SK"] = {"code": "421", "name": "SLOVAKIA"}
	country_code_name_dictionary["SL"] = {"code": "232", "name": "SIERRA LEONE"}
	country_code_name_dictionary["SM"] = {"code": "378", "name": "SAN MARINO"}
	country_code_name_dictionary["SN"] = {"code": "221", "name": "SENEGAL"}
	country_code_name_dictionary["SO"] = {"code": "252", "name": "SOMALIA"}
	country_code_name_dictionary["SR"] = {"code": "597", "name": "SURINAME"}
	country_code_name_dictionary["ST"] = {"code": "239", "name": "SAO TOME AND PRINCIPE"}
	country_code_name_dictionary["SV"] = {"code": "503", "name": "EL SALVADOR"}
	country_code_name_dictionary["SY"] = {"code": "963", "name": "SYRIAN ARAB REPUBLIC"}
	country_code_name_dictionary["SZ"] = {"code": "268", "name": "SWAZILAND"}
	country_code_name_dictionary["TC"] = {"code": "1649", "name": "TURKS AND CAICOS ISLANDS"}
	country_code_name_dictionary["TD"] = {"code": "235", "name": "CHAD"}
	country_code_name_dictionary["TG"] = {"code": "228", "name": "TOGO"}
	country_code_name_dictionary["TH"] = {"code": "66", "name": "THAILAND"}
	country_code_name_dictionary["TJ"] = {"code": "992", "name": "TAJIKISTAN"}
	country_code_name_dictionary["TK"] = {"code": "690", "name": "TOKELAU"}
	country_code_name_dictionary["TL"] = {"code": "670", "name": "TIMOR-LESTE"}
	country_code_name_dictionary["TM"] = {"code": "993", "name": "TURKMENISTAN"}
	country_code_name_dictionary["TN"] = {"code": "216", "name": "TUNISIA"}
	country_code_name_dictionary["TO"] = {"code": "676", "name": "TONGA"}
	country_code_name_dictionary["TR"] = {"code": "90", "name": "TURKEY"}
	country_code_name_dictionary["TT"] = {"code": "1868", "name": "TRINIDAD AND TOBAGO"}
	country_code_name_dictionary["TV"] = {"code": "688", "name": "TUVALU"}
	country_code_name_dictionary["TW"] = {"code": "886", "name": "TAIWAN, PROVINCE OF CHINA"}
	country_code_name_dictionary["TZ"] = {"code": "255", "name": "TANZANIA, UNITED REPUBLIC OF"}
	country_code_name_dictionary["UA"] = {"code": "380", "name": "UKRAINE"}
	country_code_name_dictionary["UG"] = {"code": "256", "name": "UGANDA"}
	country_code_name_dictionary["US"] = {"code": "1", "name": "UNITED STATES"}
	country_code_name_dictionary["UY"] = {"code": "598", "name": "URUGUAY"}
	country_code_name_dictionary["UZ"] = {"code": "998", "name": "UZBEKISTAN"}
	country_code_name_dictionary["VA"] = {"code": "39", "name": "HOLY SEE (VATICAN CITY STATE)"}
	country_code_name_dictionary["VC"] = {"code": "1784", "name": "SAINT VINCENT AND THE GRENADINES"}
	country_code_name_dictionary["VE"] = {"code": "58", "name": "VENEZUELA"}
	country_code_name_dictionary["VG"] = {"code": "1284", "name": "VIRGIN ISLANDS, BRITISH"}
	country_code_name_dictionary["VI"] = {"code": "1340", "name": "VIRGIN ISLANDS, U.S."}
	country_code_name_dictionary["VN"] = {"code": "84", "name": "VIET NAM"}
	country_code_name_dictionary["VU"] = {"code": "678", "name": "VANUATU"}
	country_code_name_dictionary["WF"] = {"code": "681", "name": "WALLIS AND FUTUNA"}
	country_code_name_dictionary["WS"] = {"code": "685", "name": "SAMOA"}
	country_code_name_dictionary["XK"] = {"code": "381", "name": "KOSOVO"}
	country_code_name_dictionary["YE"] = {"code": "967", "name": "YEMEN"}
	country_code_name_dictionary["YT"] = {"code": "262", "name": "MAYOTTE"}
	country_code_name_dictionary["ZA"] = {"code": "27", "name": "SOUTH AFRICA"}
	country_code_name_dictionary["ZM"] = {"code": "260", "name": "ZAMBIA"}
	country_code_name_dictionary["ZW"] = {"code": "263", "name": "ZIMBABWE"}

	def get_country_letter_code_name_dictionary(self):
		return self.country_code_name_dictionary
